name: CI/CD Azure

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: azure-function/

  deploy-web:
    runs-on: ubuntu-latest
    needs: deploy-function
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: web/
